### PR TITLE
Login Page without the background or files

### LINKED ISSUE #1: Login Page

### PR DESCRIPTION
**Pull request by KenzyAdel**
closes #1

### CODE REVIEW

**Review by Panda318 — COMMENTED** [review]
remove login file from project folder and from resources

**Comment by KenzyAdel** [comment]
closes #1

**Review by Panda318 — DISMISSED** [review]

**Review by Panda318 — COMMENTED** [review]
don't write code in mainwindow ,create login.h and login.cpp and login ui

**Comment by KenzyAdel** [comment]
closes #1

**Pull request closed without merging**
